### ISSUE TITLE
IQ Output ExpertSDR3 and RadioSync

### ISSUE THREAD

**Issue by EB5EA** [ExpertSDR3/ExpertSDR3-RadioSync#3]
I use RadioSync to send IQ output to third party programs, but this output has a very low level, especially in 144MHZ, in HF it is acceptable, although it went low too.
It would be possible to increase this output level or implement adjustable controls as in the sound card.

**Comment by ValeraMikhaylovsky** [comment]
In the next version, we will add an IQ gain.

**Comment by ExpertSDR3** [comment]
In the next version, we will add an IQ gain.

**Comment by EB5EA** [comment]
Muchas gracias, 🙂.
Tnx an 73.
EB5EA, Paco

**Comment by ExpertSDR3** [comment]
In the next public version will already be available the IQ gain.

![image](https://user-images.githubusercontent.com/93903520/211476774-e31f6e09-d1fe-47a3-ae88-b9338efb2ae9.png)
