### ISSUE TITLE
TCI Command via CAT

### ISSUE THREAD

**Issue by tjasperme** [ExpertSDR3/ExpertSDR3-RadioSync#4]
I would like to send TCI commands via the CAT Interface of my digi mode program to the radio.
I have requestetd it allready last year. This feature is mentoined in the release notes but it does not work.
73 Thomas

**Comment by ExpertSDR3** [comment]
Fixed a bug in the parser that led to incorrect extraction of the TCI command.
Now if you send a command to CAT:
**TC:rx_channel_enable:0,1,true;**
The command will be correctly extracted and redirected to ESDR3
![Снимок экрана от 2023-12-26 12-05-37](https://github.com/ExpertSDR3/ExpertSDR3-RadioSync/assets/93903520/3ed13bd8-26cd-413e-a7b4-75951f06a202)
